### ISSUE TITLE
Errors for #include'd .lua files that use pico-8 concise syntax [0.2.3]

### ISSUE THREAD

**Issue by hlship** [grumpydev/pico8vscodeeditor#3]
![image](https://user-images.githubusercontent.com/52660/57740713-09898b80-766e-11e9-9e60-5a09643d1ba3.png)

This code would be allowed in a .p8 file; I'd like to be able to use it in a .lua file that is in the project with my .p8 file.

**Comment by hlship** [comment]
Workaround:

Rename the file to `.p8`, and add following to top of file:

```
pico-8 cartridge // http://www.pico-8.com
version 18
__lua__
```

Change the `#include` to use the `.p8` extension.

**Comment by grumpydev** [comment]
This editor is just for p8 files, which is the extension for pico8 files, it does nothing for lua files.

**Comment by sparr** [comment]
You can manually "Change Language Mode" to pico8 when viewing your .lua file, or even configure an association of .lua files with the pico8 language, specific to your workspace or project so it doesn't affect loading lua files in other workspaces or projects.
